### PR TITLE
<style>: name -> contentName

### LINKED ISSUE #120: Ctrl-/ on entire HTML style block uses CSS comment syntax
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Atom's comment command (Ctrl-/ by default) uses CSS comment syntax when used on an HTML style block instead of the HTML comment syntax. See the gif below:

hjan6lansi

This bug occurs as long as there is at least one character (including whitespace characters) between the tags. If the block is completely empty, this issue does not occur.

Commenting out individual CSS rules within the style block works correctly (using the CSS syntax).
### Steps to Reproduce
1. Open a new or existing document with HTML syntax highlighting
2. Find or write an HTML style block that does not just immediately close (just a space or even a newline between the tags is sufficient to reproduce this issue)
3. Select the entire style block (from opening to closing tags)
4. Press Ctrl-/ (Editor: Toggle Line Comments)

**Expected behavior:** HTML comment syntax is used to comment out the style tag

**Actual behavior:** CSS comment syntax is used to (incorrectly) comment out the style tag
### Versions

Atom 1.7.4
apm 1.9.2
Windows 7 Pro SP1

### PR DESCRIPTION
**Pull request by esdoppio**
fixes #120

### CODE REVIEW

**Comment by 50Wliu** [comment]
Specs please.

**Comment by 50Wliu** [comment]
Are you still interested in finishing this PR @esdoppio?

**Comment by esdoppio** [comment]
Sure, after you merge #140.

**Comment by 50Wliu** [comment]
Superseded by #167.

**Pull request closed without merging**
