### PR TITLE
need to use a html snippet in a markdown file

### PR DESCRIPTION
**Pull request by ThunderKeg**
to use the html snippet in a markdown file

### CODE REVIEW

**Comment by 50Wliu** [comment]
Makes sense to me - /cc @atom/feedback

**Comment by lee-dohm** [comment]
I'm :-1: on this, as is. This will make files with extensions of `.md` or `.markdown` be recognized as HTML, which is not what we want.

@ThunderKeg can you give a little more information on what the ultimate goal is here?

**Comment by 50Wliu** [comment]
Oops, I thought this change was being made in the [snippets file](https://github.com/atom/language-html/blob/master/snippets/language-html.cson#L1), not the grammar one.  Thanks for catching that @lee-dohm :).

**Comment by 50Wliu** [comment]
language-html should only recognize HTML files, so I'm closing this.
We're working on including some more HTML snippets in language-gfm.

**Pull request closed without merging**
